apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: task-mgmt
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api
        image: ${DOCKER_USER}/task-api:latest
        env:
        - name: BACKEND_GRPC_ADDR
          value: "backend:50051"
        - name: BEARER_TOKEN
          valueFrom:
            secretKeyRef:
              name: api-secret
              key: bearer-token
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: "200m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
