apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongodb-pv
  namespace: task-mgmt
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:           # For demo purposes
    path: /data/mongodb  # location on k8 node's file system where data will be stored