name: Build and Push Docker Images

on:
  push:
    branches:
      - main

env:
  DOCKER_USER: ${{ secrets.DOCKER_USERNAME }}
  KUSTOMIZE_VERSION: 5.3.0

jobs:
  build-push-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push API image
        run: |
          docker buildx build --platform=linux/amd64 -f Dockerfile.api -t $DOCKER_USER/task-api:${{ github.sha }} --push .

      - name: Build and push Backend image
        run: |
          docker buildx build --platform=linux/amd64 -f Dockerfile.backend -t $DOCKER_USER/task-backend:${{ github.sha }} --push .

      - name: Install Kustomize
        run: |
          curl -sLo kustomize https://github.com/kubernetes-sigs/kustomize/releases/download/kustomize%2Fv${KUSTOMIZE_VERSION}/kustomize_v${KUSTOMIZE_VERSION}_linux_amd64.tar.gz
          tar -xzf kustomize -C /usr/local/bin/ || sudo mv kustomize /usr/local/bin/kustomize
          chmod +x /usr/local/bin/kustomize

      - name: Set image tags in kustomization.yaml
        working-directory: ./k8s
        run: |
          kustomize edit set image DOCKER_USER/task-api=DOCKER_USER/task-api:${{ github.sha }}
          kustomize edit set image DOCKER_USER/task-backend=DOCKER_USER/task-backend:${{ github.sha }}
